### ISSUE TITLE
Strange output of the parser when incorrectly closed title

### ISSUE THREAD

**Issue by bfreuden** [oblac/jodd-lagarto#13]
It is difficult for me to say if it is a bug (those common crawl html files are so crappy...).
But in case you find this useful, the following program:
```java
import jodd.lagarto.EmptyTagVisitor;
import jodd.lagarto.LagartoParser;
import jodd.lagarto.Tag;

public class Test {

    public static void main(String[] args) {
        EmptyTagVisitor visitor = new EmptyTagVisitor() {

            @Override
            public void tag(final Tag tag) {
                System.out.println("tag: " + tag.getName() + " " + tag.getType());
            }

            @Override
            public void text(final CharSequence text) {
                System.out.println("text: " + text.toString().replace("\n", "\\n"));
            }

        };
        // note the incorrect syntax: </title <meta
        String html = "<!DOCTYPE html><html><head><title>Hello World</title <meta content=\"text/html; charset=UTF-8\" http-equiv=\"content-type\" /> <meta content=\"Description\" lang=\"en-US\" name=\"description\" /></head><body></body>hello world</html> ";
        System.out.println(html.replace("<", "\n<"));
        System.out.println("---- input above / output below ----");
        LagartoParser parser = new LagartoParser(html);
        parser.parse(visitor);
    }

}
```
Produces this output (note the large text after the parse error: the parser does not seem to recover like Chrome does):
```
<!DOCTYPE html>
<html>
<head>
<title>Hello World
</title 
<meta content="text/html; charset=UTF-8" http-equiv="content-type" /> 
<meta content="Description" lang="en-US" name="description" />
</head>
<body>
</body>hello world
</html> 
---- input above / output below ----
tag: html START
tag: head START
tag: title START
text: Hello World
tag: title SELF_CLOSING
text:  <meta content="Description" lang="en-US" name="description" /><body>hello world 
```

**Comment by igr** [comment]
Thanx! I will look into more details, just a quick note first:

`LagartoParser` does not do recovery. `LagartoDomParser` does, using the HTML rules (well, the major subset, I really could not implement them all). And with the so-called "plus mode" (yeah, my naming is not the best), you got some more recoveries: https://lagarto.jodd.org/lagarto-dom/parsing-modes

**Comment by bfreuden** [comment]
You're welcome!
Thank you for pointing this out. I certainly used the wrong term :-)
I was referring to the fact that, when encountering crappy/invalid html, the ``LagartoParser`` is rightfully reporting errors like "Parse error: invalid token", but keeps on "emitting" "tokens" afterwards. 
In this case it seems to fall into a state where everything after this lexer/parser error is considered as a single "text token".

**Comment by igr** [comment]
Huh; this one is really weird. After reading the HTML5 spec, I see that Jodd is following the tokenization more/less correctly; but I need to double-check this in the morning.

**Comment by bfreuden** [comment]
Good hunt! :)

**Comment by igr** [comment]
Finally fixed! This was good one!

Sorry for a long wait, I got too much work in December.

**Comment by bfreuden** [comment]
Well done! 👍
No worries! You're super responsive if you ask me :-) 
Thanks a lot!
