### ISSUE TITLE
TagWriter unnecessarily closes script tag

### ISSUE THREAD

**Issue by bartektartanus** [oblac/jodd-lagarto#14]
Simple example with TagWriter
```java
String scriptText = '<script src="abc.js"/>';
LagartoParser parser = new LagartoParser(scriptText);
StringBuilder stringBuilder = new StringBuilder();
TagVisitor vistor = new TagWriter(stringBuilder);
parser.parse(vistor);
System.out.println(stringBuilder.toString());
```
This code prints:
```html
<script src="abc.js"/></script>
```
so it rewrites self closing tag and then adds additional end tag.

`LagartoDomBuilder` generates this HTML using the same input:
```html
<script src="abc.js"></script>
```

I think it should either rewrite tag "as is" (without end tag) or rewrite it like `LagartoDomBuilder`.

**Comment by igr** [comment]
Ah, I have this special _case_ for the `script` tag that always appends the closing tag... Fixing!

**Comment by bartektartanus** [comment]
Good job! Any plans to release a new version with that fix? :)

**Comment by igr** [comment]
Very soon (i.e. this week), just want to fit in the fix for the other issue!
