### ISSUE TITLE
LagartoParser and self-closing script tag

### ISSUE THREAD

**Issue by bartektartanus** [oblac/jodd-lagarto#15]
I'm using LagartoParser with TagWriter and this is the content:
```html
<script src="a.js"/>
<link href="b.html">
<script src="c.js"></script>
```
I think it should call `script` method for first tag, then `tag` method with `link` and `script` again for the last tag. But instead `LagartoParser` calls `TagWriter` only once - for first `script` tag with `src="a.js"` and body equal to
```html
<link href="b.html">
<script src="c.js">
```
and body is simply rewritten as-is.

I'm not sure if this is wrong behavior as `script` tag should be always closed like this:
`<script></script>`
but maybe there should be another method in that parser to clear this script tags? I'm parsing html content from user and it would be inconvenient to enforce them to correct this.

What do you think about it?

**Comment by igr** [comment]
That is actually the correct behavior, here is how it looks in Chrome, its only one script tag:

![image](https://user-images.githubusercontent.com/2280001/103162477-6c06af80-47f1-11eb-8816-384aff44f143.png)

I am not sure atm if there is a way to easily 'override' this behavior.
