### ISSUE TITLE
getTagPosition not correct with multi-byte unicode

### ISSUE THREAD

**Issue by RXminuS** [oblac/jodd-lagarto#21]
I'm still digging down exactly where this happens but it seems that multi-byte characters aren't correctly translated into byte positions in the source. For instance if you insert something like 👨‍👨‍👦‍👦 (4 bytes) into your html you'll see that all the tag positions following this text will be offset by the amount of bytes missed for the single character (so 3 bytes off from that point on)

**Comment by igr** [comment]
Hey @RXminuS! Is this still a valid issue?
