### ISSUE TITLE
Have options for controlling logging levels or lower existing ones.

### ISSUE THREAD

**Issue by slandelle** [oblac/jodd-lagarto#5]
See https://stackoverflow.com/questions/64094701/gatling-script-works-fine-but-prints-j-l-d-lagartodombuildertagvisitor-unclose

Generally speaking, ERROR logging level is for unrecoverable crashes. This is not how Lagarto, not browsers, behaves on malformed input. HTML living spec states that malformed input should just be ignored.

Maybe different users have different needs.

Maybe for some users detecting malformed content is critical and they want WARN (or maybe even ERROR), but users parsing HTML at scale, such as Gatling, don't want to spam logging with such not blocking messages (we'd rather use INFO).

**Comment by slandelle** [comment]
Basically, it looks like I'm asking for restoring `parsingErrorLogLevel` from Lagarto 5.

**Comment by igr** [comment]
Makes sense!

**Comment by slandelle** [comment]
I'll provide a PR.

**Comment by igr** [comment]
I can do that, no worries, its just a flag @slandelle

**Comment by igr** [comment]
btw, you can disable errors at all by setting `collectErrors` to false

**Comment by slandelle** [comment]
Nah. `collectErrors` is set to `false` by default and anyway: https://github.com/oblac/jodd-lagarto/blob/v6.0.1/src/main/java/jodd/lagarto/dom/LagartoDOMBuilderTagVisitor.java#L513

**Comment by igr** [comment]
Ah, true, its an OR operation there.

**Comment by slandelle** [comment]
I have a workaround for now (overriding InfoLogLagartoDOMBuilder and InfoLogLagartoDOMBuilderTagVisitor) so I'm not in a rush.

**Comment by igr** [comment]
I would add a `BiConsumer<Log, String>` property instead of a level @slandelle, as SLf4j does not have levels and would not like to add custom Lagarto levels.

would that make sense for you?

e.g. setErrorLogConsumer((log, msg) -> log.info(msg))

**Comment by slandelle** [comment]
I don't think a single method interface is enough. You need 2 methods or parameters:

1. one for performing the actual logging
2. one for deciding if logging is enabled and if not save the message allocation

**Comment by slandelle** [comment]
* https://github.com/oblac/jodd-lagarto/blob/master/src/main/java/jodd/lagarto/dom/LagartoDOMBuilderTagVisitor.java#L109-L111
* https://github.com/oblac/jodd-lagarto/blob/master/src/main/java/jodd/lagarto/dom/LagartoDOMBuilderTagVisitor.java#L219-L221
* https://github.com/oblac/jodd-lagarto/blob/master/src/main/java/jodd/lagarto/dom/LagartoDOMBuilderTagVisitor.java#L354-L356

**Comment by ADNinfo** [comment]
Related to the above StackOverflow issue, I'm getting "Parse error: invalid character reference" on &goto= http arguments in href values and "invalid token" errors on . Are those really malformed inputs?

**Comment by igr** [comment]
@ADNinfo just to be sure if I understood correctly, are you talking about these two cases?

case 1
```html
<a href="foo.com&goto=23">x</a>
```

case 2
```html
<!-- foo--bar -->
```

**Comment by ADNinfo** [comment]
Exactly, here are real examples, just in case they are actually malformed...
Not easy to locate in an UTF-8 html file, I had to convert from UTF-8 to ASCII so the offsets in the info messages would match.

Case 1: 
`<a href="../solapCore/annulerTransaction?RECURSIF=true&goto=/solapCore/transactionSouscription" id="lienCreationContrat" class="lien_std">Création d'un contrat</a>`

Case 2: (between two div )
`<!-- ------- IDENTIFICATION DEBUT ------- //-->`

**Comment by igr** [comment]
I will check this in more details, but out of my head now:

+ case 1 - `&` should be always encoded as `&amp;`, hence the warning
+ case 2 - its a bug, should not emit anything, will fix

**Comment by igr** [comment]
Closing this one, @ADNinfo  opening new issue to fix it.

**Comment by mareru** [comment]
I have the same issues as reported on the SO while running the Gatling script.
```
03:20:09.303 [ERROR] j.l.d.LagartoDOMBuilderTagVisitor - Parse error: invalid token [@15136]
03:20:09.350 [ERROR] j.l.d.LagartoDOMBuilderTagVisitor - Parse error: invalid character reference [@40337]
03:20:10.374 [ERROR] j.l.d.LagartoDOMBuilderTagVisitor - Parse error: invalid character reference [@52319]
03:20:10.374 [ERROR] j.l.d.LagartoDOMBuilderTagVisitor - Parse error: invalid token [@108321]
03:20:10.374 [ERROR] j.l.d.LagartoDOMBuilderTagVisitor - Parse error: invalid character reference [@131962]
03:20:12.557 [ERROR] j.l.d.LagartoDOMBuilderTagVisitor - Parse error: invalid character reference [@52333]
03:20:12.563 [ERROR] j.l.d.LagartoDOMBuilderTagVisitor - Parse error: invalid token [@100170]
03:20:12.563 [ERROR] j.l.d.LagartoDOMBuilderTagVisitor - Parse error: invalid character reference [@123811]

Can you help?
```

**Comment by igr** [comment]
@mareru these are common logs when a page is parsed - HTML pages commonly contain issues that are not up to the HTML standard.

I added two configurations in `LagartoDomBuilderConfig`:

+ `errorLogEnabled`
+ `errorLogConsumer`

that could be used for filtering and turning off the logs.

That being said, maybe Gatling guys are already using these for reducing the logs. @slandelle is that true? Maybe @mareru just needs to upgrade Gatling?

**Comment by slandelle** [comment]
> maybe Gatling guys are already using these for reducing the logs

Indeed, see https://github.com/gatling/gatling/blob/master/gatling-core/src/main/scala/io/gatling/core/check/css/Lagarto.scala#L30-L39.

> Maybe @mareru just needs to upgrade Gatling?

Most likely, yes
