### ISSUE TITLE
Strange output of the parser with self closing title

### ISSUE THREAD

**Issue by bfreuden** [oblac/jodd-lagarto#7]
Since this is my first comment here: thank you for this beautiful project (having the position of tags relative to the input is brilliant!)

I am using Lagarto 6.0.2:
```groovy
    implementation group: 'org.jodd', name: 'jodd-lagarto', version: '6.0.2'
```

And I can observe a strange behavior of the parser with the following program (note the odd self-closing title):
```java
import jodd.lagarto.EmptyTagVisitor;
import jodd.lagarto.LagartoParser;
import jodd.lagarto.Tag;

public class Test {

    public static void main(String[] args) {
        EmptyTagVisitor visitor = new EmptyTagVisitor() {

            @Override
            public void tag(final Tag tag) {
                System.out.println("tag: " + tag.getName() + " " + tag.getType());
            }

            @Override
            public void text(final CharSequence text) {
                System.out.println("text: " + text);
            }

        };
        System.out.println("Run 1");
        // note the odd self-closing title: <title />
        LagartoParser parser = new LagartoParser("<html><head><title /></head><body>hello world!</body></html>");
        parser.parse(visitor);

        System.out.println("Run 2");
        // note the correct title: <title></title>
        parser = new LagartoParser("<html><head><title></title></head><body>hello world!</body></html>");
        parser.parse(visitor);
    }

}

```
Here is the output (note the ``<body>hello world!`` text sequence):
```
Run 1
tag: html START
tag: head START
tag: title SELF_CLOSING
text: <body>hello world!
Run 2
tag: html START
tag: head START
tag: title START
tag: title END
tag: head END
tag: body START
text: hello world!
tag: body END
tag: html END
```
It does not seem to be correct.

**Comment by igr** [comment]
Huh, good catch. Thank you for the test!

For some reason, the parsers go to RCDATA state, instead of DATA.

**Comment by igr** [comment]
I am on the track to solve the issue. The good news is that this happens only with TITLE and TEXTAREA - as those are the only two RCDATA tags.

**Comment by igr** [comment]
And you can disable the `enableRawTextModes` flag to fix the issue temporarily.

**Comment by bfreuden** [comment]
Wow! That's great! Thank you too!
I have finished testing the parser on some common crawl data, this one specifically (2 GB of HTML): 
`aws s3 cp s3://commoncrawl/crawl-data/CC-MAIN-2014-10/segments/1394023864559/warc/CC-MAIN-20140305125104-00002-ip-10-183-142-35.ec2.internal.warc.gz  ./`
I will submit 3 new bugs but that's all I have encountered so far.
Again: thank you for this impressive library!

**Comment by igr** [comment]
Thank you! Just checked, it seems it's not a bug:) The `title` and `textarea` are really different. See what chrome renders:

![image](https://user-images.githubusercontent.com/2280001/99913847-36563e80-2cfa-11eb-8ad5-1b7a8dddb9a2.png)

Need to put this in the documentation :)

It seems that bug is that title has to contain the remaining text :)

**Comment by bfreuden** [comment]
You're right! :+1: 
I'm truly for the incorrect bug report.

**Comment by igr** [comment]
No worries, there is still a bug with the special case in this RCDATA mode, working on it now 👍
